<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="12371" started-at="2017-10-29T17:13:52Z" finished-at="2017-10-29T17:14:04Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="12371" started-at="2017-10-29T17:13:52Z" finished-at="2017-10-29T17:14:04Z">
      <class name="com.screenshots.TestCaptureScreenshot">
        <test-method status="PASS" signature="BeforeTest()[pri:0, instance:com.screenshots.TestCaptureScreenshot@6d4b1c02]" name="BeforeTest" is-config="true" duration-ms="9357" started-at="2017-10-29T18:13:52Z" finished-at="2017-10-29T18:14:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeTest -->
        <test-method status="FAIL" signature="f()[pri:0, instance:com.screenshots.TestCaptureScreenshot@6d4b1c02]" name="f" duration-ms="17" started-at="2017-10-29T18:14:01Z" finished-at="2017-10-29T18:14:01Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Facebook - Log In or Sign Up] but found [Facebook]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Facebook - Log In or Sign Up] but found [Facebook]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.screenshots.TestCaptureScreenshot.f(TestCaptureScreenshot.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="AfterTest()[pri:0, instance:com.screenshots.TestCaptureScreenshot@6d4b1c02]" name="AfterTest" is-config="true" duration-ms="2141" started-at="2017-10-29T18:14:02Z" finished-at="2017-10-29T18:14:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterTest -->
      </class> <!-- com.screenshots.TestCaptureScreenshot -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
